
all: ls3.c show_file_info.c mode_to_letters.c uid_to_name.c gid_to_name.c do_ls.c dostat.c
	gcc -g ls3.c  \
   show_file_info.c \
   mode_to_letters.c \
   uid_to_name.c \
   gid_to_name.c \
   do_ls.c \
   dostat.c \
   -o ls3.exe
